### ISSUE TITLE
Need to update readme 

### ISSUE THREAD

**Issue by RPG-Alex** [RPG-Alex/rust-micro-cms#38]
The readme is stil referencing the sqlx crate, and we have switched to r2d2 and rusqlite.

**Comment by matiangelico** [comment]
I would like to work in this issue. Could you assign it to me? Thanks

**Comment by RPG-Alex** [comment]
Absolutely! Thanks for helping out! Please fork the repo then when you push the update please push it [to this branch](https://github.com/RPG-Alex/rust-micro-cms/tree/38-need-to-update-readme).

**Comment by RPG-Alex** [comment]
Apologies, I must have linked this issue incorrectly and closed it the other day. @matiangelico are you still up for working on this? It should be a simple fix, if not please let me know and I'll update the read me soon.
