### ISSUE TITLE
User API Endpoints

### ISSUE THREAD

**Issue by RPG-Alex** [RPG-Alex/rust-micro-cms#9]
Create RESTful endpoints for user registration, login, and management.

**Comment by Stipulations** [comment]
Hello, i have a project that is exactly this, if you want you can use it for inspiration https://github.com/Stipulations/user_management

it is a work in progress but it will have everything you need and more once finished

**Comment by RPG-Alex** [comment]
Thanks. This is an interesting module. At the moment I actually switched direction as I wanted to experiment with a singular login for the blog owner using [webauthn](https://webauthn.io/) . Welcome to contribute to this feature as I have been mainly focusing on my frontend recently.
